### ISSUE TITLE
Teams Screen Page Error

### ISSUE THREAD

**Issue by Prashant2504** [developer-student-club-thapar/mobile-app#16]
Currently the Team Screen is not being displayed normally. 
Here's how it looks like currently

![Screenshot_2020-04-19-13-37-03-847_com dsctiet mobileapp](https://user-images.githubusercontent.com/30950368/80492211-52227d80-8981-11ea-8173-26c3df7d03bf.jpg)

Another interesting thing i found was that when you scroll down and other team members data load in. It works perfectly fine, but then if you go up suddenly the previous team members are now replaced with the latest one. Here's an example. I went all the way down to load the blockchain members and then scrolled back up. Here the Machine learning members got repalced with blockchain members. And notice how there's an error to right, that's because there was only 1 blockchain member but since it loaded that data in ML Members, the empty card created an error as no relevant data was put into it. 

![Screenshot_2020-04-27-05-43-20-535_com dsctiet mobileapp](https://user-images.githubusercontent.com/30950368/80492491-bb09f580-8981-11ea-8311-bc9d4e15a123.jpg)

The cause of the issue is probably to with indexing and the file causing this is most likely this one -
mobile-app/lib/widgets/member_detail_card.dart

Prior to changes in this, it was working perfectly fine. Refer to commit: 43ba024033198cca51d6204bc82ba3e6c1aff3df - (Commit Message - firebase)
 for the stable version of team screen.

**Comment by ramyak-mehra** [comment]
Fixed the indexing of the loading widgets
Only thing left is to fix the future builder

**Comment by WantGuns** [comment]
is this issue being taken care of ? i would like to take a look into this and possibly propose a fix.

**Comment by ramyak-mehra** [comment]
fixed using caching the images
