### ISSUE TITLE
Add network check at the loading screeen

### ISSUE THREAD

**Issue by ramyak-mehra** [developer-student-club-thapar/mobile-app#20]
Add some kind of internet checking at the loading screen. If the network is not available inform the user and display cached data 
Also, do error check while calling the backend API

**Comment by rrkas** [comment]
I can implement network check.
Please assign me this issue.

**Comment by rrkas** [comment]
can you please tell which screen do you mean by loading screen.

**Comment by rrkas** [comment]
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:26: Error: Type 'DiagnosticableMixin' not found.
class PictureStream with DiagnosticableMixin {
                         ^^^^^^^^^^^^^^^^^^^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:44: Error: Type 'DiagnosticableMixin' not found.
abstract class PictureStreamCompleter with DiagnosticableMixin {
                                           ^^^^^^^^^^^^^^^^^^^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:88:7: Error: The type 'DiagnosticableMixin' can't be mixed in.
class PictureStream with DiagnosticableMixin {
      ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:192:16: Error: The type 'DiagnosticableMixin' can't be mixed in.
abstract class PictureStreamCompleter with DiagnosticableMixin {
               ^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:167:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(properties);
          ^^^^^^^^^^^^^^^^^^^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:171:30: Error: The method 'toStringShort' isn't defined for the class 'PictureStreamCompleter'.
 - 'PictureStreamCompleter' is from 'package:flutter_svg/src/picture_stream.dart' ('../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart').
Try correcting the name to the name of an existing method, or defining a method named 'toStringShort'.
      ifPresent: _completer?.toStringShort(),
                             ^^^^^^^^^^^^^
../../Documents/Development/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_svg-0.17.4/lib/src/picture_stream.dart:266:11: Error: Superclass has no method named 'debugFillProperties'.
    super.debugFillProperties(description);
          ^^^^^^^^^^^^^^^^^^^


FAILURE: Build failed with an exception.


The project uses libraries that contain errors.

**Comment by ramyak-mehra** [comment]
@rrkas I have updated the libraries. The newer version of flutter had some breaking changes you can pull the latest changes.

**Comment by rrkas** [comment]
@ramyak-mehra please tell in which screen/page i have to implement the network check

**Comment by ramyak-mehra** [comment]
> @ramyak-mehra please tell in which screen/page i have to implement the network check

I guess at the home page it would be a good idea to check internet connection and everywhere else we can do good error handling.
What do you think?

**Comment by rrkas** [comment]
Ok. I'm on it

**Comment by rrkas** [comment]
I upgraded the flutter sdk to 1.23
Still SVG plugin was showing error. I then tried removing the plugin and its usage in project and tried to run.
Then, this error shows. I checked, google-services.json file was missing in project/app directory.
Please look into the matter.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugGoogleServices'.
> File google-services.json is missing. The Google Services Plugin cannot function without it. 
   Searched Location: 
  myDir/mobile-app/android/app/src/nullnull/debug/google-services.json
  myDir/mobile-app/android/app/src/debug/nullnull/google-services.json
  myDir/mobile-app/android/app/src/nullnull/google-services.json
  myDir/mobile-app/android/app/src/debug/google-services.json
  myDir/mobile-app/android/app/src/nullnullDebug/google-services.json
  myDir/mobile-app/android/app/google-services.json

**Comment by ramyak-mehra** [comment]
Checkout out the readme for setting up the project

**Comment by rrkas** [comment]
oh. ok. got it.

**Comment by rrkas** [comment]
please see pull request #21 
there is conflict in pubspec.yaml & pubspec.lock files, but the internet check functionality is working fine

**Comment by Bhupendrapt5** [comment]
Is this issue still on? if yes, can I work on it?

**Comment by ramyak-mehra** [comment]
> Is this issue still on? if yes, can I work on it?

I was a bit busy to update. This has been resolved i am closing it, there are some more issues you can check or if you find any you can also post.
